### ISSUE TITLE
Import to Joplin

### ISSUE THREAD

**Issue by RedHorseMane** [tjnull/TJ-OSINT-Notebook#2]
I tried to import the .jex file to Joplin, but received an error message: 'Could not decompress"/Users/[]/Downloads/TJ-OSINT_notebook-v1.jex." The file may be corrupted. Error was: invalid entry'
The downloaded .jex file is 857 KB
Perhaps I'm doing something wrong?

**Comment by tjnull** [comment]
I checked the jex file and it was successful to import into Joplin. I think you need to redownload the file and try again. 

Depending on what OS you are using you can download the whole git repo and it will have jex file with it.

**Comment by RedHorseMane** [comment]
Downloaded the repo and all working perfectly. Thank you for the resource!
